notifications:
  email: false

language: node_js

node_js:
  - '4'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

before_script: "npm run-script local-webserver 2>&1 >/dev/null &"

script: "eslint test/**/*.js && wdio wdio.BUILD.conf.js"
